#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-model-guachi-deployment
spec:
  selector:
    matchLabels:
      app: heart-model-guachi-server
  replicas: 1
  template:
    metadata:
      labels:
        app: heart-model-guachi-server
    spec:
      containers:
      - name: heart-model-guachi-container
        #image: gcr.io/tensorflow-serving/resnet 
        image: docker.io/aldotr/fastapiml:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: heart-model-guachi-service
  name: heart-model-guachi-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: heart-model-guachi-server
  type: LoadBalancer
